import React from 'react'

function FutureKund() {
  return (
    <div className='flex flex-col gap-2 bg-gray-100 py-10'>
        <h1 className='text-center text-xl sm:text-2xl font-semibold'>Online Free Kundli For Future Predictions</h1>
        <h3 className='text-center text-lg sm:text-xl text-gray-500 font-light'>Get Your Kundli by Date of Birth</h3>

        <div className='mt-2 flex flex-col gap-2 px-12 whitespace-normal '>
            <p className='text-slate-600 font-light'>The Kundli of a person is one of the most sought aspects of astrology. A Kundali entails the details about the positions of stars and planets at the time of your birth based on which further predictions are made. And with further predictions, we mean predictions about different aspects of one's life like love, career, health, business, finance, and even marriage. Simply said, Kundli making is a necessary thing for any individual and is likely to improve their decision-making capabilities gradually in the course of time.</p>
            <p className='text-slate-600 font-light'>A Janam Kundli is made after studying the exact position of planets at the time you were born and based on the same, one’s Sun sign, Moon sign, and other such astrological aspects are listed. The Kundali is a co-existence of predictions and charts that help the astrologer learn about what your future would be like, the times you will have to grind harder, and also the times when luck will be by your side in abundance.</p>
            <p className='text-slate-600 font-light'>However, with the culture shift, people are getting very tech-savvy and seek things under their thumb. And for the same reason, the Janam Kundali making process has also gone online, making it more pocket-friendly, accessible, and detailed. We at AstroTalk, for the convenience of the huge user base of ours, provide them with free Janam kundali online so anyone and everyone has the luxury of learning more about themselves and thus can plan their life better</p>
             <p className='text-slate-600 font-light'>However, we also often bump into people who wonder if this online kundali astrology is accurate and if it has the same essence of the physical Kundli making process? Or is getting a Kundli made by a pandit or Vedic astrologer still the best option? To be honest, a Kundli made by a Vedic astrologer surely takes the top spot (which our astrologers can make for you), but an online Kundli software is no less when it comes to precision. Honestly, an online Kundli can be more detailed when compared to the physical ones.</p>
            <p className='text-slate-600 font-light'>However, we also often bump into people who wonder if this online kundali astrology is accurate and if it has the same essence of the physical Kundli making process? Or is getting a Kundli made by a pandit or Vedic astrologer still the best option? To be honest, a Kundli made by a Vedic astrologer surely takes the top spot (which our astrologers can make for you), but an online Kundli software is no less when it comes to precision. Honestly, an online Kundli can be more detailed when compared to the physical ones.</p>
            <p className='font-semibold'>How To Create a Free Online Janam Kundli?</p>
            <p className='text-slate-600 font-light'>Creating an online Kundli for yourself is relatively easy. Honestly, butter-easy. All you need to do to make your online Janam Kundli with AstroTalk is simply go to the ‘Kundli’ option and Insert the requested information. The requested information would be your date of birth, time of your birth, etc. The correct date and time allow precise predictions.</p>
            <p className='text-slate-600 font-light'>Once you have filled in the details, all you need to do is click submit. Once you click submit, within seconds, you will find a detailed Janam Kundli of yourself. Besides textual content (that will help you understand what strong or weak traits you have), the Janam Kundli will also help you with charts that will showcase the position of the different planets in houses based on your current astrological situation, which reveals a whole new dimension of information.</p>
             <p className='text-slate-600 font-light'>The free Janam Kundli you get on <span className='font-semibold '>AstroTalk</span>, though, is made after a precise study of all the scientific methods but when it comes to writing it down, the study is portrayed in a very simple language so you can understand it without any hassle. However, just in case you hit a snag or can’t understand what it means, simply chat or ring our astrologers to help you with your queries.</p>
            <p  className='text-slate-600 font-light'>Besides getting a Janam Kundli for yourself, we also offer <span className='font-semibold'>Janam Kundli matching</span> service to anyone seeking. Janam kundli matching is most important when one plans to get married. Matching of kundlis is done to ensure the girl and boy planning to get married are compatible with each other. This, however, doesn’t mean that if kundli doesn't match one shouldn’t marry the other person. But in case kundli doesn't match, an astrologer can let you know why it did not, and also recommend remedies for the same.</p>
            <p className='text-slate-600 font-light'>Janam Kundli matching is related to Gun matching. Janam Kundli of two people, when matched, shows how many guns of those people match. Based on this, marriages are fixed. With Janam Kundli matching, you can also understand how being Manglik of two people will affect each other, what could be the effect of Manglik dosh on you, and remedies to get rid of Manglik dosha.</p>
            <p className='text-slate-600 font-light'>These were just a handful of times when Janam Kundli could come in handy. So if looking to get one for yourself, get in touch with our astrologers for the best advice and service.</p>
            <p className='text-slate-600 font-light'>To get your online Janam Kundli, Kundli prediction, and kundali reading, you can either <span className='font-semibold'>chat with our astrologer</span>  or <span className='font-semibold'>talk to our astrologer</span>. For free online Kundli making, you can also visit the free Janam Kundli chart option and get a personalised free Janam kundali for yourself by our Janam Kundli maker software. You can get free kundali check and free Kundli prediction.</p>
        </div>

    </div>
  )
}

export default FutureKund